### ISSUE TITLE
How should I build this project?

### ISSUE THREAD

**Issue by RemyYang** [LouieYang/AgeAndGenderEstimation#1]
Hello, Louie Yang. Thank you so much for releasing your source code. However, I am wondering how I should build this project. Should I add this source code into caffe and re-make caffe again or should I independently build this project? Would you please help me out? Thank you so much!

**Comment by LouieYang** [comment]
For this question, you should independently build this project and you can view caffe there as a lib like boost. But I suggest you read the source code cpp_classification.cpp in the caffe example file

**Comment by RemyYang** [comment]
Thank you Louie Yang, install caffe with cmake would solve my problem. Star your project!
